repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  #- id: fix-encoding-pragma # ruff does not thing this makes sense
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ["--maxkb=2000"]

# # Convert relative imports to absolute imports
# - repo: https://github.com/MarcoGorelli/absolufy-imports
#   rev: v0.3.1
#   hooks:
#   - id: absolufy-imports

# Find common spelling mistakes in comments and docstrings
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: ['--ignore-regex="(\b[A-Z]+\b)"', '--ignore-words-list=fom'] # Ignore capital case words, e.g. country codes
    types_or: [python, rst, markdown]
    files: ^(scripts|doc)/

# Make docstrings PEP 257 compliant
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    args: ["--in-place", "--make-summary-multi-line"]

- repo: https://github.com/keewis/blackdoc
  rev: v0.3.9
  hooks:
  - id: blackdoc
    additional_dependencies: ["black==23.3.0"]

# Linting with ruff
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.1.6'
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

# # Check for FSFE REUSE compliance (licensing)
# - repo: https://github.com/fsfe/reuse-tool
#   rev: v1.1.2
#   hooks:
#   - id: reuse
