repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  #- id: fix-encoding-pragma # ruff does not thing this makes sense
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ["--maxkb=2000"]

# Find common spelling mistakes in comments and docstrings
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: ['--ignore-regex="(\b[A-Z]+\b)"', '--ignore-words-list=fom'] # Ignore capital case words, e.g. country codes
    types_or: [python, rst, markdown]
    files: ^(scripts|doc)/

- repo: https://github.com/roy-ht/pre-commit-jupyter
  rev: v1.2.1
  hooks:
    - id: jupyter-notebook-cleanup
      args:
        # - --remove-kernel-metadata
        - --pin-patterns
        - "[pin];[donotremove]"

# Run ruff to lint and format
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.4
  hooks:
    # Run the linter.
  - id: ruff
    args: [--fix]
    # Run the formatter.
  - id: ruff-format

# # Check for FSFE REUSE compliance (licensing)
# - repo: https://github.com/fsfe/reuse-tool
#   rev: v1.1.2
#   hooks:
#   - id: reuse
