# tox enviroments that run on both pull requests and merge to main
name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      # fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.11] # to minimise complexity we only test a min and a max version
        # you can separate the tox-envs in different .yml files
        # see version 0.10.1
        # https://github.com/coroa/pandas-indexing/releases/tag/v0.10.1
        # below the list of tox envs that you wish to include in the matrix
        include:
          # on all platforms and versions do everything
          - tox-envs: [lint, test, docs, build]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install tox
      run: |
        python -m pip install tox

    - name: Run tox environments for testing
      run: tox -e ${{ join(matrix.tox-envs, ',') }}

    # from https://github.com/codecov/codecov-action
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        #fail_ci_if_error: true
        verbose: true
